#!/bin/bash

TOKEN=$TOKEN
CHAT_ID=$CHAT_ID
MESSAGE=$MESSAGE $TRAVIS_COMMIT $TRAVIS_COMMIT_MESSAGE $TRAVIS_EVENT_TYPE $TRAVIS_PULL_REQUEST_BRANCH
URL="https://api.telegram.org/bot$TOKEN/sendMessage"

curl -s -X POST $URL -d chat_id=$CHAT_ID -d text="$MESSAGE"
