# Generated by Django 2.1.7 on 2019-02-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190223_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='1', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
