# Generated by Django 2.1.7 on 2019-03-03 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190303_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=uuid.UUID('e6164c46-3dc0-11e9-aea0-34363bd100e2'), editable=False, unique=True),
        ),
    ]
